project:
  type: book
  output-dir: docs

book:
  title: "data_792"
  author: "Julia Cardwell"
  date: "2/12/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - data_exploration.qmd
    - describing_spatial_data.qmd
    - tmap.qmd
    - hw2.qmd
    - covid.qmd
    - map_competition.qmd
    - wrangling.qmd
    - spatial_wrangling.qmd
    - analytical_datasets.qmd
    - analyticaldatasetworkshop.qmd
    - ppa.qmd
    - hw4.qmd
    - ppaworkshop.qmd

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

