# Group Workshop: Analytical Dataset

This group workshop is designed to assess ability to apply spatial feature engineering concepts.

### Instructions

1.  Create a new .Rmd named LASTNAME1LASTNAME2.Rmd (include all last names in your group)

2.   Complete the following tasks. Your .Rmd file should be organized so that each task has a text header, a code chunk, comments for each command, and any written components directly under the chunk.

**Reading Data**

-   Load the `tidyverse` , `tmap`, `terra`, and `sf` libraries

-   Read in the data using the following commands:

    ```{r, eval = F}
    #all ems stations across the triangle region
    triangle_ems <- st_read("https://drive.google.com/uc?export=download&id=1JYZxoM3GB43AnSY2mKW1p_ixeBBh1CBJ")

    #all census blocks across the triangle region
    triangle_blocks <- st_read("https://drive.google.com/uc?export=download&id=1Q6f9wPXrN0NMZJZkAR9OFkneCfxIBiOl")

    #all census blocks across chapel hill
    ch_blocks <- st_read("https://drive.google.com/uc?export=download&id=14Jhu9ZQDRL14lQGiTUKcqqrsQcooH6BU")

    #raster of average summer temp in ch (in celcius)
    ch_summer_heat <- rast("https://drive.google.com/uc?export=download&id=1qvJepSdhFTiKZIAyn76VA9xvlIM8f5s8")

    #raster of canopy cover in ch (% per pixel)
    ch_canopy_cover <- rast("https://drive.google.com/uc?export=download&id=1a5MibyiyAJgxIqTxzSBOoMNqklErlIVR")

    ```

**Analytic Dataset #1**

For this analytic dataset you should create a new object that adds two columns to the `ch_blocks` object. One column, `av_heat` should be the average summer heat across each block. The second column, `av_canopy` should be the average tree canopy across each block.

After creating the analytic dataset, create a scatterplot (`dataset |> ggplot(aes(x = VARIABLE1, y= VARIABLE2) + geom_point()`) that shows the relationship between summer heat and canopy coverage across Chapel Hill.

Below the code chunk, write a brief interpretation of the relationship shown in the scatterplot.

**Analytic Dataset #2**

For this analytic dataset you should create a new object that adds a column to the `triangle_blocks` object. The new column (`count_ems`) should include a count of each EMS station that is within 5 miles of the block group.

After creating the analytic dataset, create a basic map that displays the `count_ems` variable across the triangle.

Below the code chunk, write a brief interpretation of the spatial pattern of the map.
